        CREATE TABLE IF NOT EXISTS t_weather_log (
            index_nbr INT NOT NULL,
            ymd TEXT NOT NULL,
            Local_Pressure_Average REAL NOT NULL,
            Sea_Level_Pressure_Average REAL NOT NULL,
            Total_Precipitation REAL NOT NULL,
            Maximum_1_Hour_Precipitation REAL NOT NULL,
            Maximum_10_Minute_Precipitation REAL NOT NULL,
            Average_Temperature REAL NOT NULL,
            Maximum_Temperature REAL NOT NULL,
            Minimum_Temperature REAL NOT NULL,
            Average_Humidity REAL NOT NULL,
            Minimum_Humidity REAL NOT NULL,
            Average_Wind_Speed REAL NOT NULL,
            Maximum_Wind_Speed REAL NOT NULL,
            Maximum_Wind_Speed_Direction TEXT NOT NULL,
            Maximum_Instantaneous_Wind_Speed REAL NOT NULL,
            Maximum_Instantaneous_Wind_Speed_Direction TEXT NOT NULL,
            Sunshine_Duration REAL NOT NULL,
            Total_Snowfall TEXT NOT NULL,
            Maximum_Snow_Depth TEXT NOT NULL,
            Weather_Summary_Daytime TEXT NOT NULL,
            Weather_Summary_Nighttime TEXT NOT NULL,
            CONSTRAINT index_nbr_pk primary key(index_nbr,ymd)
            ) 